spring:
  application:
    name: service-goods
  datasource: 
    url: jdbc:mysql://localhost:3306/cloud_goods?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
---spring:  activemq:    broker-url: tcp://localhost:61616
    user: admin
    password: admin  
    in-memory: false
    
 
 #  activemq:
#    broker-url: tcp://172.25.253.182:61616
#    user: admin
#    password: admin
        # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
          #是否启用内存模式（就是不安装MQ，项目启动时同时启动一个MQ实例）
#    in-memory: false
     # 结束前等待时间
#    close-timeout: 10s
      #等待小时响应时间  0 永远
#    send-timeout: 0
#    packages:
#      trust-all: true
#    pool:
#      enabled: false   
mybatis:
 #pojo类所在包路径
  type-aliases-package: cn.cloud.goods_api.goods.entity
  mapper-locations:
  - classpath:mapper/*xml
    
mapper:
  mappers: 
  - cn.cloud.goods_api.util.MyMapper
  not-empty: false
  identity: MYSQL   

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  




