server:
  port: 8767
  
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka/


zuul:  routes:    api-a:
      path: /api-a/**
      service-id: service-ribbon
    api-b:
      path: /api-b/**
      service-id: service-feign        
        
       